---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: azure
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-azure-centos7-jenkins
    platform: centos7
    assign_public_ip: true
    vm_size: Standard_D2s_v3
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - rhel_family

  - name: test-azure-ubuntu16-jenkins
    platform: ubuntu16
    assign_public_ip: false
    vm_size: Standard_D2s_v3
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - debian_family

  - name: test-azure-ubuntu18-jenkins
    platform: ubuntu18
    assign_public_ip: false
    vm_size: Standard_D2s_v3
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - debian_family

  - name: test-azure-Debian9-jenkins
    platform: debian9
    assign_public_ip: false
    vm_size: Standard_D2s_v3
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - debian_family

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  playbooks:
    create: ../resources/provisioning/AZURE/create.yml
    prepare: ../resources/provisioning/AZURE/prepare.yml
    destroy: ../resources/provisioning/AZURE/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-azure-direct
verifier:
  name: ansible
  lint:
    name: ansible-lint
