---
- name: "Set Credentials"
  jenkins_script:
    url: "http://localhost:{{ jenkins2_config.http_port }}"
    script: "{{ lookup('template', 'set-credentials.groovy.j2') }}"
    user: '{{ jenkins2.cli_username }}'
    password: '{{ jenkins2.cli_password }}'
    validate_certs: False
    timeout: 120
