---
- name: "Force gathering facts"
  hosts: all
  gather_facts: True
  roles: []

- name: "Converge"
  hosts: jenkins_master
  roles:
    - role: lean_delivery.java
    - role: lean_delivery.jenkins
